### ISSUE TITLE
Welcome to add a provider to kvrpc:)

### ISSUE THREAD

**Issue by zhiqiangxu** [alash3al/goukv#1]
kvrpc is a universal rpc layer for arbitrary kv database:

https://github.com/zhiqiangxu/kvrpc

**Comment by alash3al** [comment]
Do you mean that we need to think about implementing kvrpc interface?

**Comment by zhiqiangxu** [comment]
> Do you mean that we need to think about implementing kvrpc interface?

Yes, any vendor just needs to implement kvrpc.KVDB interface in order to be integrated into kvrpc:)

**Comment by alash3al** [comment]
that is fine, but I think that the main domain for goukv is to be just a wrapper for other stores but to make an external interface it should be in another repo i.e goukv-service, there we can implement the rpc, redis, ... etc.

**Comment by zhiqiangxu** [comment]
> that is fine, but I think that the main domain for goukv is to be just a wrapper for other stores but to make an external interface it should be in another repo i.e goukv-service, there we can implement the rpc, redis, ... etc.

Right, it can be in another repo like `goukv-service`, or just as a provider in kvrpc :)

**Comment by alash3al** [comment]
Yep!
